// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfqzzjbmcfgbhczeyrjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmcXp6amJtY2ZnYmhjemV5cmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NDAzNjAsImV4cCI6MjA1OTExNjM2MH0.qJ4NH86kK3wvNVHligNyzl2yM_LcBp5wxrYko2fLoxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);